name: tempo-alchemist-ci
on:
  push:
    paths:
      - 'tempo-alchemist/**'
      - '.github/workflows/tempo-alchemist-ci.yml'
  pull_request:
    paths:
      - 'tempo-alchemist/**'
      - '.github/workflows/tempo-alchemist-ci.yml'
jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: tempo-alchemist
    steps:
      - uses: actions/checkout@v4
      - name: Build Docker image
        run: docker build -t tempo-alchemist:ci .
